// Anime data store

export const animeData = {
  1: {
    id: 1,
    title: "Demon Slayer: Kimetsu no Yaiba",
    originalTitle: "鬼滅の刃",
    rating: 9.2,
    year: 2019,
    type: "TV",
    episodes: 55,
    status: "Finished",
    ageRating: "R - 17+",
    duration: "24 min",
    studios: "ufotable",
    genres: ["Action", "Fantasy", "Supernatural"],
    description: "Tanjiro Kamado, a kindhearted boy who sells charcoal for a living, finds his family slaughtered by a demon. The sole survivor is his sister Nezuko, who has been transformed into a demon. To avenge his family and cure his sister, Tanjiro begins rigid training to become a demon slayer.",
    seasons: [
      { id: 1, name: "Season 1", episodes: 26, year: "2019" },
      { id: 2, name: "Season 2 - Mugen Train", episodes: 7, year: "2021" },
      { id: 3, name: "Season 3 - Entertainment District", episodes: 11, year: "2022" },
      { id: 4, name: "Season 4 - Swordsmith Village", episodes: 11, year: "2023" },
    ],
    poster: "/assets/images/poster/1.jpg",
    cover: "/assets/images/cover/1.jpg",
  },
  2: {
    id: 2,
    title: "Attack on Titan",
    originalTitle: "進撃の巨人",
    rating: 9.1,
    year: 2013,
    type: "TV",
    episodes: 87,
    status: "Finished",
    ageRating: "R - 17+",
    duration: "24 min",
    studios: "Wit Studio, MAPPA",
    genres: ["Action", "Drama", "Fantasy"],
    description: "人类一直在与来自神秘种族的巨大生物泰坦(Titan)战斗。泰坦占据着人类世界的大部分领土，只剩下最后一堵墙保护着人类的最后领土。当最大的泰坦之一突破墙壁时，一切都变了。",
    seasons: [
      { id: 1, name: "Season 1", episodes: 25, year: "2013" },
      { id: 2, name: "Season 2", episodes: 12, year: "2017" },
      { id: 3, name: "Season 3", episodes: 12, year: "2018" },
      { id: 4, name: "Final Season", episodes: 16, year: "2021" },
    ],
    poster: "/assets/images/poster/2.jpg",
    cover: "/assets/images/cover/2.jpg",
  },
  3: {
    id: 3,
    title: "Jujutsu Kaisen",
    originalTitle: "呪術廻戦",
    rating: 8.9,
    year: 2020,
    type: "TV",
    episodes: 47,
    status: "Finished",
    ageRating: "R - 17+",
    duration: "23 min",
    studios: "MAPPA",
    genres: ["Action", "Fantasy", "Supernatural"],
    description: "A boy swallows a cursed talisman - the finger of a demon - and becomes host to the curse itself. In a world where curses lurk in every shadow, Yuji Itadori is determined to use his newfound powers to help people.",
    seasons: [
      { id: 1, name: "Season 1", episodes: 24, year: "2020" },
      { id: 2, name: "Season 2", episodes: 23, year: "2023" },
    ],
    poster: "/assets/images/poster/3.jpg",
    cover: "/assets/images/cover/3.jpg",
  },
  4: {
    id: 4,
    title: "Chainsaw Man",
    originalTitle: "チェンソーマン",
    rating: 8.7,
    year: 2022,
    type: "TV",
    episodes: 12,
    status: "Finished",
    ageRating: "R - 17+",
    duration: "24 min",
    studios: "MAPPA",
    genres: ["Action", "Fantasy", "Horror"],
    description: "Denji is a young man stuck in poverty, working as a devil hunter for the yakuza. After being killed by the zombie devil, Pochita, he merges with the devil to become Chainsaw Man - a human with devil powers.",
    seasons: [
      { id: 1, name: "Season 1", episodes: 12, year: "2022" },
    ],
    poster: "/assets/images/poster/4.jpg",
    cover: "/assets/images/cover/4.jpg",
  },
  5: {
    id: 5,
    title: "Spy x Family",
    originalTitle: "スパイファミリー",
    rating: 8.8,
    year: 2022,
    type: "TV",
    episodes: 37,
    status: "Ongoing",
    ageRating: "PG-13",
    duration: "24 min",
    studios: "Wit Studio, CloverWorks",
    genres: ["Action", "Comedy", "Adventure"],
    description: "For the mission to infiltrate an elite school, Agent Twilight must create a fake family. He adopts an orphaned girl named Anya, not knowing she's a telepath, and marries a woman named Yor - who happens to be an assassin.",
    seasons: [
      { id: 1, name: "Season 1", episodes: 12, year: "2022" },
      { id: 2, name: "Season 2", episodes: 12, year: "2023" },
      { id: 3, name: "Season 3", episodes: 13, year: "2025" },
    ],
    poster: "/assets/images/poster/5.jpg",
    cover: "/assets/images/cover/5.jpg",
  },
  6: {
    id: 6,
    title: "My Hero Academia",
    originalTitle: "僕のヒーローアカデミア",
    rating: 8.4,
    year: 2016,
    type: "TV",
    episodes: 138,
    status: "Finished",
    ageRating: "PG-13",
    duration: "24 min",
    studios: "Bones",
    genres: ["Action", "Comedy", "Superhero"],
    description: "In a world where almost everyone has superpowers, quirkless boy Izuku Midoriya dreams of becoming a hero. After meeting the greatest hero All Might, he receives a chance to attend hero academy and fulfill his destiny.",
    seasons: [
      { id: 1, name: "Season 1", episodes: 13, year: "2016" },
      { id: 2, name: "Season 2", episodes: 25, year: "2017" },
      { id: 3, name: "Season 3", episodes: 25, year: "2018" },
      { id: 4, name: "Season 4", episodes: 25, year: "2019" },
      { id: 5, name: "Season 5", episodes: 25, year: "2021" },
      { id: 6, name: "Season 6", episodes: 25, year: "2022" },
    ],
    poster: "/assets/images/poster/6.jpg",
    cover: "/assets/images/cover/6.jpg",
  },
  7: {
    id: 7,
    title: "One Piece",
    originalTitle: "ワンピース",
    rating: 9.0,
    year: 1999,
    type: "TV",
    episodes: "ongoing",
    status: "Ongoing",
    ageRating: "PG-13",
    duration: "24 min",
    studios: "Toei Animation",
    genres: ["Action", "Adventure", "Comedy"],
    description: "Monkey D. Luffy sets off on an adventure with his pirate crew in hopes of finding the greatest treasure ever, known as the One Piece. The story follows him and his crew as they battle powerful foes and make new friends.",
    seasons: [
      { id: 1, name: "East Blue Saga", episodes: 61, year: "1999" },
      { id: 2, name: "Alabasta Saga", episodes: 78, year: "2001" },
      { id: 3, name: "Sky Island Saga", episodes: 39, year: "2003" },
      { id: 4, name: "Water 7 Saga", episodes: 78, year: "2004" },
    ],
    poster: "/assets/images/poster/7.jpg",
    cover: "/assets/images/cover/7.jpg",
  },
  8: {
    id: 8,
    title: "Naruto",
    originalTitle: "ナルト",
    rating: 8.5,
    year: 2002,
    type: "TV",
    episodes: 220,
    status: "Finished",
    ageRating: "PG-13",
    duration: "23 min",
    studios: "Pierrot",
    genres: ["Action", "Adventure", "Martial Arts"],
    description: "Naruto Uzumaki, a young ninja with a demon fox sealed inside him, dreams of becoming the Hokage - the leader of his village. Follow his journey as he grows from an outcast to a powerful ninja.",
    seasons: [
      { id: 1, name: "Part 1", episodes: 220, year: "2002" },
    ],
    poster: "/assets/images/poster/8.jpg",
    cover: "/assets/images/cover/8.jpg",
  },
  9: {
    id: 9,
    title: "Solo Leveling",
    originalTitle: "俺だけレベルアップな件",
    rating: 9.0,
    year: 2024,
    type: "TV",
    episodes: 12,
    status: "Finished",
    ageRating: "R",
    duration: "24 min",
    studios: "A-1 Pictures",
    genres: ["Action", "Fantasy", "Adventure"],
    description: "In a world where hunters must battle deadly monsters to protect humanity, Sung Jinwoo, the weakest of all hunters, finds himself alone after being the sole survivor of a double dungeon raid. But after being chosen for a mysterious quest, he alone can level up.",
    seasons: [
      { id: 1, name: "Season 1", episodes: 12, year: "2024" },
    ],
    poster: "/assets/images/poster/9.jpg",
    cover: "/assets/images/cover/9.jpg",
  },
  10: {
    id: 10,
    title: "Frieren: Beyond Journey's End",
    originalTitle: "葬送のフリーレン",
    rating: 9.1,
    year: 2023,
    type: "TV",
    episodes: 28,
    status: "Finished",
    ageRating: "PG-13",
    duration: "24 min",
    studios: "Madhouse",
    genres: ["Adventure", "Fantasy", "Drama"],
    description: "After the demon king is defeated, the hero party's mage Frieren returns to her solitary life. Decades later, she finally understands what it means to have companions as she reflects on her journey and the fleeting nature of life.",
    seasons: [
      { id: 1, name: "Season 1", episodes: 28, year: "2023" },
    ],
    poster: "/assets/images/poster/10.jpg",
    cover: "/assets/images/cover/10.jpg",
  },
  11: {
    id: 11,
    title: "Dragon Ball Super",
    originalTitle: "ドラゴンボール超",
    rating: 7.9,
    year: 2015,
    type: "TV",
    episodes: 131,
    status: "Finished",
    ageRating: "PG",
    duration: "23 min",
    studios: "Toei Animation",
    genres: ["Action", "Adventure", "Comedy"],
    description: "After the battle with Majin Buu, Earth is at peace once again. Gokuu and his friends are back training and preparing for new adventures. They soon face the God of Destruction Beerus and other powerful beings from other universes.",
    seasons: [
      { id: 1, name: "God of Destruction", episodes: 14, year: "2015" },
      { id: 2, name: "Universe 6", episodes: 19, year: "2016" },
      { id: 3, name: "Tournament of Power", episodes: 30, year: "2017" },
      { id: 4, name: "Galactic", episodes: 57, year: "2018" },
      { id: 5, name: "Super Hero", episodes: 26, year: "2022" },
    ],
    poster: "/assets/images/poster/11.jpg",
    cover: "/assets/images/cover/11.jpg",
  },
  12: {
    id: 12,
    title: "Vinland Saga",
    originalTitle: "ヴィンランド・サガ",
    rating: 8.8,
    year: 2019,
    type: "TV",
    episodes: 48,
    status: "Finished",
    ageRating: "R - 17+",
    duration: "24 min",
    studios: "WIT Studio",
    genres: ["Action", "Drama", "Adventure"],
    description: "Thors Snorresson was a legendary Viking warrior who retired from battle to raise his son, Thorfinn. But when Thors is killed by the mercenary Askeladd, Thorfinn swears to avenge his father and become a warrior.",
    seasons: [
      { id: 1, name: "Season 1", episodes: 24, year: "2019" },
      { id: 2, name: "Season 2", episodes: 24, year: "2024" },
    ],
    poster: "/assets/images/poster/12.jpg",
    cover: "/assets/images/cover/12.jpg",
  },
}

// Get all anime as a list
export const getAllAnime = () => Object.values(animeData)

// Get anime by ID
export const getAnimeById = (id) => animeData[id] || null

// Get related anime (excluding current)
export const getRelatedAnime = (currentId, limit = 5) => {
  return Object.values(animeData)
    .filter(anime => anime.id !== currentId)
    .slice(0, limit)
}

// Generate episodes for an anime
export const generateEpisodes = (anime) => {
  return anime.seasons.flatMap((season) =>
    Array.from({ length: season.episodes }, (_, i) => ({
      id: `${anime.id}-${season.id}-${i + 1}`,
      animeId: anime.id,
      seasonId: season.id,
      seasonName: season.name,
      number: i + 1,
      title: `Episode ${i + 1}`,
      duration: "24:15",
      isNew: season.id === anime.seasons[anime.seasons.length - 1].id && 
             i === anime.seasons[anime.seasons.length - 1].episodes - 1,
      isWatched: i < 3 && season.id === 1,
      progress: i === 2 && season.id === 1 ? 65 : 0,
    }))
  )
}

// Sample comments for anime
export const getSampleComments = (animeTitle) => [
  { 
    id: 1, 
    user: "AnimeMaster99", 
    avatar: "👤", 
    text: `This is absolutely incredible! ${animeTitle} never disappoints with its storytelling.`, 
    time: "2 hours ago", 
    likes: 234 
  },
  { 
    id: 2, 
    user: "OTAKU_King", 
    avatar: "🎭", 
    text: `The animation quality is top-notch. Best anime of its generation!`, 
    time: "5 hours ago", 
    likes: 189 
  },
  { 
    id: 3, 
    user: "WeebHunter", 
    avatar: "⚔️", 
    text: "Can't stop watching! The character development is phenomenal.", 
    time: "1 day ago", 
    likes: 156 
  },
]
